### ISSUE TITLE
css 使用 letter-spacing 在华为手机上有兼容性问题。

### ISSUE THREAD

**Issue by linj0218** [ChrisChan13/wxml2canvas-2d#24]
css：
![Image](https://github.com/user-attachments/assets/9375294b-f1ef-476b-887e-258a9e5d2f22)

在华为上的问题截图：
![Image](https://github.com/user-attachments/assets/9c4818a3-780a-4d73-a9b0-f6fcccbd10a4)

```html
    ...
    <view class="wxml2canvas-item price-line">
          <view class="wxml2canvas-item left">
            <view class="wxml2canvas-item unit" data-text="￥">
              ￥
            </view>
            <view
              class="wxml2canvas-item integer font-wcss-m"
              data-text="19"
            >
              19
            </view>
            <view
              class="wxml2canvas-item decimals font-wcss-m"
              data-text="90"
            >
              90
            </view>
            <view class="wxml2canvas-item suffix" data-text="最低到手价">
              最低到手价
            </view>
          </view>
          <view
            class="wxml2canvas-item right"
            data-text="已售111"
          >
            已售111
          </view>
        </view>
    ...
``` 
```css
    ...
    .price-line {
          margin-top: 8px;
          display: flex;
          justify-content: space-between;
          .left {
            flex: 1;
            overflow: hidden;
            display: flex;
            align-items: baseline;
            .unit {
              text-indent: -2px;
              margin-right: -2px;
            }
            .unit, .decimals {
              color: #FF5036;
              font-size: 20px;
              font-weight: 500;
              line-height: 20px;
              // letter-spacing: -1px;
            }
            .integer {
              color: #FF5036;
              font-size: 28px;
              font-weight: 500;
              line-height: 28px;
              // letter-spacing: -1.4px;
            }
            .suffix {
              margin-left: 4px;
              color: #FF5036;
              font-size: 13px;
              line-height: 13px;
            }
          }
          .right {
            padding-top: 10px;
            color: #9D9D9D;
            font-size: 12px;
            line-height: 12px;
          }
        }
    ...
``` 
使用版本："wxml2canvas-2d": "^1.2.5"；
复现条件：css 中使用 letter-spacing: -1px 属性，且数字里包含“1”；
暂时避开使用 letter-spacing 属性，将 letter-spacing 去掉后就正常了。

**Comment by ChrisChan13** [comment]
@linj0218 `letter-spacing` 目前不支持在真机设备上使用！开发时发现设置画布的 `letter-spacing` 和 `word-spacing` 等样式在开发工具和 Windows 上有效，但真机（不止华为）上无效。所以设置该样式后，页面上文字的间距缩小，所占空间也变小。但真机的画布上设置间距无效，导致文字占用空间不变，所以绘制时会出现换行。
<br>
![Image](https://github.com/user-attachments/assets/dd03efbf-0c02-4684-9d53-22ac32ee0b3c)
<br>
更多样式和 API 的兼容情况，可以查看 [README](https://github.com/ChrisChan13/wxml2canvas-2d/blob/main/README.md) 中的 **CSS 属性支持情况** 以及 **使用注意**！

**Comment by ChrisChan13** [comment]
如若必须要缩小文字间距，目前可以将文字内容拆分，用 `margin` 替代实现！

**Comment by linj0218** [comment]
@ChrisChan13 哦哦，好的，我换个方案。

**Comment by linj0218** [comment]
@zyanfly 作者不是说 letter-spacing 属性还不支持么，用 space-between 就能生效？

**Comment by ChrisChan13** [comment]
@linj0218 @zyanfly `flex` 布局也是一种方法，因为和设置 `margin` 一样，本质上都需要将文字拆分成多个 `text`。

两种方法对比如下：
1. 使用 `margin`：
``` html
<view class="title wxml2canvas-item">
  <text class="wxml2canvas-item" data-text="1">1</text>
  <text class="wxml2canvas-item" data-text="9">9</text>
  <text class="wxml2canvas-item" data-text=".">.</text>
  <text class="wxml2canvas-item" data-text="9">9</text>
  <text class="wxml2canvas-item" data-text="9">9</text>
</view>
```
``` css
.title {}
.title text {
  margin: 0 -0.5px;
}
```
2. 使用 `flex`：
``` html
<view class="title wxml2canvas-item">
  <text class="wxml2canvas-item" data-text="1">1</text>
  <text class="wxml2canvas-item" data-text="9">9</text>
  <text class="wxml2canvas-item" data-text=".">.</text>
  <text class="wxml2canvas-item" data-text="9">9</text>
  <text class="wxml2canvas-item" data-text="9">9</text>
</view>
```
``` css
.title {
  letter-spacing: -1px;
  display: flex;
  justify-content: space-between;
}
```

两种方法能达到相似的效果，但两种方法最终呈现的效果还是有一点差别。
由于本组件在调用 `CanvasContext.fillText` 方法时会传入 `maxWidth` 属性，传入 `maxWidth` 将限制文字渲染的最大宽度。
此处限制最大宽度的作用是： `CanvasContext.measureText` 方法测量的文字宽度，与实际渲染时的文字宽度之间存在误差。
若不限制最大宽度，有可能出现文字渲染时的宽度超过测量时的宽度，而本组件对超出渲染范围的内容是采取剪切的操作。

所以需要 `maxWidth` 的宽度限制，回到前面的两种方法中。
采用 `flex` 的方法需要依然保留 `letter-spacing` 属性，这样会使每个文字的宽度变窄。但在画布中 `letter-spacing` 又不生效，这时 `maxWidth` 属性会将文字的宽度压扁。当然 -1px 可能看不出来，将间距再缩小就比较明显。
采用 `margin` 方法的话没有了 `letter-spacing` 属性，每个文字宽度不变，只是发生了位移，所以绘制出来的效果更接近页面中的表现。但也有个小坑，`margin` 模拟 -1px `letter-spacing` 的话，首个文字 `margin-left` 为 -1px，末尾文字 `margin-right` 为 0，其余文字 `margin-left` 和 `margin-right` 均为 -0.5px。

结论是在本组件的情况下，使用 `margin` 较为合适。
